### ISSUE TITLE
Error downloading 

### ISSUE THREAD

**Issue by Leo121** [ambiot/amb1_arduino#1]
Error downloading https://github.com/ambiot/amb1_arduino/raw/master/Arduino_package/package_realtek.com_ameba1_index.json
Skipping contributed index file /home/leo/Dev_Tools/arduino-1.8.12-linux64_RTLDuino/arduino-1.8.12/portable/package_realtek.com_ameba1_index.json, parsing error occured:
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (FileInputStream); line: 7, column: 2]

**Comment by M-ichae-l** [comment]
Hi, @Leo121 
I have checked the download process. I did not reproduce your situation. Recommend you to use the latest ArduinoIDE and AMEBA1 package. With link [https://github.com/ambiot/amb1_arduino/raw/master/Arduino_package/package_realtek.com_ameba1_index.json]
If you still receive error downloading. Please reply to me with a full log from Arduino IDE.

**Comment by ambiot** [comment]
There is no further response for a long time. Seems the issue is solved.
