### ISSUE TITLE
can uvc here suport rtl8722dm ?

### ISSUE THREAD

**Issue by chenbaijian** [ambiot/amb1_arduino#10]
hello
i find that :  rtl8722dm support lcd and hs usb, but do not have uvc demo in arduino
how ever:  rtl 8195am do not support lcd controller, so if i want to display uvc camera pictures on a lagre lcd,  i must move uvc driver and  demo from here(ameba1) to  armeba d。 
will it works?

**Comment by M-ichae-l** [comment]
@chenbaijian  
Hi, this is a feature request for [ambd_arduino](https://github.com/ambiot/ambd_arduino). It is being processed now. 
There is another hardware that supports video better. If you are interest please refer to [AMB82 MINI](https://www.amebaiot.com/en/ameba-arduino-summary/)
